aws_region = "ap-south-1"
vpc_cidr = "10.10.0.0/16"
public_subnet_cidr_a = "10.10.0.0/24"
public_subnet_cidr_b = "10.10.1.0/24"
availability_zones   = ["ap-south-1a", "ap-south-1b"] # Optional if using dynamic AZs
instance_type = "t3.micro"
ssh_key_name = "linux" # set to your EC2 keypair name if you want SSH access
ssh_cidr = "0.0.0.0/0"
db_password = "MySecurePass123!"
