pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/kesavandevops/devops-portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("flask-cicd-app", "./01-ci-cd-pipeline")
                }
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
                // you could add pytest or unit tests here
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker tag flask-cicd-app $DOCKER_USER/flask-cicd-app:latest
                    docker push $DOCKER_USER/flask-cicd-app:latest
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f 01-ci-cd-pipeline/k8s-manifests/'
            }
        }
    }
}
