apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: green
  template:
    metadata:
      labels:
        app: flask-app
        version: green
    spec:
      containers:
      - name: flask-app
        image: kesavan07/flask-cicd-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_COLOR
          value: "green"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
