apiVersion: v1
kind: Service
metadata:
  name: flask-service-lb
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - port: 80        # Port exposed by LoadBalancer
      targetPort: 5000 # Port your Flask app listens on in the container
