name: Destroy Serverless API Infrastructure (Terraform)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1
      TF_VERSION: 1.9.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::326052702112:role/GitHubOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initialize Terraform with backend
        working-directory: 05-serverless-aws/terraform
        run: terraform init -input=false

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        working-directory: 05-serverless-aws/terraform
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
